n1 = str(input('Digite uma frase qualquer: ')).strip()
n10 = n1.lower()
n2 = n1.count('A')
n3 = n1.count('a')
n4 = (len(n1) - n1.count(' '))
a = n1.find('A')
b = n1.find('a')
c = n3 + n2
d = n10.count('a')
print('Sua frase possue um total de {} A'.format(n2))
print('Sua frase possuem um total de {} a'.format(n3))
print('O primeiro *A* aparece na posição {}'.format(a))
print('O *a* aparece na posição {}'.format(b))
print('Última posição que aparece a letra *a* {}'.format(d))